[package]
name = "leet_code"
version = "0.1.0"
authors = ["Peter <PeterRong96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["local_testing"]
local_testing = []

[dependencies]